# Generated by Django 5.2.11 on 2026-03-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donation_date',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
