# Generated by Django 5.2.11 on 2026-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_remove_donorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
