# Generated by Django 5.2.11 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
