# Generated by Django 5.2.11 on 2026-03-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_donorprofile_latitude_donorprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='town_village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/Village'),
        ),
    ]
