# Generated by Django 5.2.11 on 2026-03-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
