# Generated by Django 5.2.11 on 2026-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
